### ISSUE TITLE
Infinite loading on analysis board

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#585]
**Exact URL where the bug happened**

https://lishogi.org/analysis

(that's the only link that provides analysis that I checked. Can maybe be reproduce in game/study analysis board or any other analysis pages on lishogi) 

**Steps to reproduce the bug**

Open analysis board and play and move (other than P-76) and wait for analysis. 

**What did you expect to happen?**

Position gets analyzed by YaneuraOu. 

**What happened instead?**

Page loads infinitely.

**Operating system and browser version**

- PC Chrome
- Mobile (Android) Chrome
- Not sure what else

**Related forum post**

https://lishogi.org/forum/lishogi-feedback/yaneuraou-does-not-work

Edit: I just noticed that I face this error only when I change memory, cpu or multiple line.

**Comment by WandererXII** [comment]
Thanks for reporting this. The default hash size for YaneuraOu was way too high, I lowered that.
Also limited the wasm memory (taken mostly from https://github.com/lichess-org/lila/commit/38bb35f15465ee22f5a580f1d12b4b23926eb97a).
Also fixed some bugs, where 16 hash value was just ignored.
It should be better now, but it still might crash on some devices. Let's keep this open and monitor it.

If YaneuraOu crashes for anyone reading this, please leave a comment with the position you tried to analyse, settings you used (memory, cpu, multiPV) and your device.

**Comment by killerducky** [comment]
https://lishogi.org/analysis/standard/ln3g3/1r2g4/p1ppsp1k1/4pbp2/1p6l/2PPSP3/PPB1P1PPP/3R2GKs/LN4G2_w_SNLPnp_1?color=sente

When I turn on engine, it just says "loading" forever. I didn't see any errors in console. Tried logged in on Chrome, and also as guest using icognito Edge.

**Comment by WandererXII** [comment]
Thanks for reporting it, should be fixed now.

**Comment by vrublack** [comment]
I still encounter this bug on an iPhone SE 2020 and iPad (with both Safari and Chrome) regardless of the engine settings.

**Comment by WandererXII** [comment]
> I still encounter this bug on an iPhone SE 2020 and iPad (with both Safari and Chrome) regardless of the engine settings.

Should be solved with #615.

Feel free to open a new issue if the issue persists.
