### ISSUE TITLE
“Learn”: “Let’s go” button is disabled in mobile browsers

### ISSUE THREAD

**Issue by Lishkon** [WandererXII/lishogi#74]
Encountered this issue when was trying to show the shogi basics to my daughter on iPhone 7/Safari|Chrome. It looks like the button is clickable when you tap it d'or the first time, but no response is followed and further actions are blocked. You can't even close the screen and refreshing the page doesn't help as well.

iOS version: 14.1
Chrome version: 86.0.4240.93
![image](https://user-images.githubusercontent.com/3415689/99854467-89f74980-2b8d-11eb-9227-de23add3c9ed.jpeg)

**Comment by WandererXII** [comment]
Hello, thanks for submitting this. That's some weird behavior. I will try to look into it.

**Comment by WandererXII** [comment]
Same thing happening on lichess - [https://github.com/ornicar/lila/issues/7591](https://github.com/ornicar/lila/issues/7591). I will monitor this.

**Comment by Lishkon** [comment]
It's also strange that the section name above the button is written in camelCase. It looks like it is a mere class name somehow displayed.

**Comment by WandererXII** [comment]
> It's also strange that the section name above the button is written in camelCase. It looks like it is a mere class name somehow displayed.

Fixed, there was a missing translation line.

**Comment by TheYoBots** [comment]
I am still facing this issue on iPad Air 2, iOS 14.4.2, safari browser updated to latest version.

https://user-images.githubusercontent.com/73843275/115019840-59ff6880-9ed7-11eb-930d-44a6603e0ccc.MP4

**Comment by benediktwerner** [comment]
It's fixed on lichess now after ornicar#8778, ornicar#8798, and ornicar#8800 (the latter two just fixing issues with the first PR).
